"""Generate L2/L3 skeleton JSONs from L1 manifests for the 28 v2/v3 anchors.

Per `pwm-team/coordination/MAINNET_BLOCKERS_2026-04-30.md` Part 1 item C1.
Replaces the unrealistic "author 29 spec/benchmark pairs by hand in one
session" with a more honest two-step workflow:

1. **This script** emits a valid skeleton L2 (spec) + L3 (P-benchmark)
   per L1 anchor. Each skeleton:
   - Inherits Ω parameter space, gate_class, physics_fingerprint, and
     other relevant fields from the parent L1 manifest
   - Marks the s1_s4_gates as "PENDING" (honest — not yet validated)
   - Inserts placeholder strings for fields that genuinely need
     physics-specific hand authoring (epsilon_fn formula, baseline
     names + expected_psnr, dataset construction method, etc.)
   - Sets `v2_v3_skeleton: true` so downstream tooling knows the file
     is a placeholder

2. **Per-Principle hand-authoring** (or Bounty #7) fills in the
   placeholders with the physics-specific details the L1 author /
   domain expert knows. The skeletons reduce per-Principle authoring
   time by ~70% (the ~30% remaining is the genuinely hard part:
   epsilon_fn calibration, baseline curation, dataset choice).

Coverage:
- L1-503..L1-510 — 8 v3 standalone multi-physics medical imaging
- L1-511 PillCam optical core
- L1-512..L1-517 — 6 v2 PWDR (PillCam-bleeding, DR, chest-CT, mammography, MRS, dermoscopy)
- L1-518 XRD analytical core
- L1-519 — XRD space-group PWDR
- L1-520..L1-525 — 6 v2 PWDR (RNA-seq, drug-target, earthquake, pneumothorax, stroke-CTP, PE-CTPA)
- L1-526..L1-531 — 6 v2 PWDR (bone-fracture, OA-KL, ECG, glaucoma, AMD, EEG seizure)

Total: 28 L1 anchors → 28 L2 + 28 L3 = 56 skeleton files.

Usage:

    python3 scripts/generate_l2_l3_skeletons.py
    python3 scripts/generate_l2_l3_skeletons.py --dry-run  # plan only
    python3 scripts/generate_l2_l3_skeletons.py --force-overwrite  # rewrite existing skeletons

Outputs:
    Each L1 manifest's directory gets sibling L2 + L3 files. E.g., for
    L1-503 QSM at:
      pwm-team/content/agent-imaging/principles/C_medical_imaging/L1-503_qsm.json
    the script writes:
      pwm-team/content/agent-imaging/principles/C_medical_imaging/L2-503_qsm.json
      pwm-team/content/agent-imaging/principles/C_medical_imaging/L3-503_qsm.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _repo_root() -> Path:
    cur = Path(__file__).resolve()
    for p in [cur, *cur.parents]:
        if (p / "pwm-team").is_dir():
            return p
    raise RuntimeError("cannot find repo root")


# Anchor IDs in scope for this generator
TARGET_L1_IDS = {f"L1-{n}" for n in range(503, 532)}


def _find_l1_files(repo: Path) -> list[Path]:
    """Find all L1 manifests for L1-503..L1-531 across the content tree."""
    out: list[Path] = []
    content = repo / "pwm-team" / "content"
    for p in content.rglob("L1-*.json"):
        try:
            data = json.loads(p.read_text())
        except json.JSONDecodeError:
            continue
        if data.get("artifact_id") in TARGET_L1_IDS:
            out.append(p)
    return sorted(out)


def _build_l2_skeleton(l1: dict) -> dict:
    """Produce a valid L2 spec skeleton inheriting from L1."""
    aid = l1["artifact_id"]
    num = aid.split("-")[1]
    parent_l1 = aid

    spec_range = l1.get("spec_range", {})
    center = spec_range.get("center_spec", {})

    # Six-tuple: derive from L1
    omega = {dim: spec_range.get("omega_bounds", {}).get(dim, "[NEEDS_HAND_AUTHORING: bounds]")
             for dim in spec_range.get("allowed_omega_dimensions", [])}

    epsilon_fn = center.get("epsilon_fn_center", "[NEEDS_HAND_AUTHORING: scaling formula in problem parameters]")

    skeleton = {
        "artifact_id": f"L2-{num}",
        "layer": "L2",
        "parent_l1": parent_l1,
        "principle_ref": f"sha256:<L1-{num}_principle_hash>",
        "title": f"{l1.get('title', aid)} — Spec Skeleton",
        "spec_type": "mismatch_only",
        "v2_v3_skeleton": True,
        "skeleton_note": "Auto-generated by scripts/generate_l2_l3_skeletons.py 2026-05-01. Per-Principle hand-authoring required to: (a) populate epsilon_fn with calibrated scaling formula, (b) curate 3+ baseline solver records, (c) enumerate ibenchmark tier_bounds, (d) write s1_s4_justifications. See PWM_PART1_C1_STATUS.md for the per-Principle authoring queue.",

        "six_tuple": {
            "omega": omega,
            "E": {
                "forward": l1.get("E", {}).get("forward_model",
                                                "[NEEDS_HAND_AUTHORING: closed-form forward operator]"),
                "operator": center.get("forward_operator",
                                        "[NEEDS_HAND_AUTHORING: operator name]"),
                "primitive_chain": l1.get("G", {}).get("dag",
                                                        "[NEEDS_HAND_AUTHORING: DAG primitive chain]"),
                "inverse": "[NEEDS_HAND_AUTHORING: what the solver recovers]"
            },
            "B": {
                "non_negativity": True,
                "physical_realizability": "[NEEDS_HAND_AUTHORING: domain-specific constraints]"
            },
            "I": {
                "strategy": "zero_init"
            },
            "O": l1.get("error_metric_secondary", "[NEEDS_HAND_AUTHORING: observable list]") if isinstance(l1.get("error_metric_secondary"), list) else [
                l1.get("error_metric", "PSNR_dB"),
                l1.get("error_metric_secondary", "SSIM") if isinstance(l1.get("error_metric_secondary"), str) else "SSIM"
            ],
            "epsilon_fn": epsilon_fn
        },

        "protocol_fields": {
            "input_format": "[NEEDS_HAND_AUTHORING: solver input shape + dtype]",
            "output_format": "[NEEDS_HAND_AUTHORING: solver output shape + dtype]",
            "baselines": [
                {"name": "[NEEDS_HAND_AUTHORING: baseline 1]", "method_sig": "L+O", "expected_score": None},
                {"name": "[NEEDS_HAND_AUTHORING: baseline 2]", "method_sig": "L+N", "expected_score": None},
                {"name": "[NEEDS_HAND_AUTHORING: baseline 3]", "method_sig": "L+N", "expected_score": None}
            ]
        },

        "ibenchmark_range": {
            "center_ibenchmark": {
                "rho": 1,
                "omega_tier": {dim: center.get("omega", {}).get(dim,
                                "[NEEDS_HAND_AUTHORING: nominal value]")
                              for dim in spec_range.get("allowed_omega_dimensions", [])},
                "epsilon": "[NEEDS_HAND_AUTHORING: nominal-tier threshold]"
            },
            "tier_bounds": spec_range.get("omega_bounds", {}),
            "proximity_threshold": 0.10
        },

        "d_spec": 0.50,
        "d_spec_notes": "Skeleton — per-Principle authoring required to compute d_spec against existing specs under same L1 (none yet for v2/v3 anchors).",

        "gate_class": l1.get("gate_class", "analytical"),
        "s1_s4_gates": ["PENDING", "PENDING", "PENDING", "PENDING"],
        "s1_s4_justifications": {
            "S1": "[NEEDS_HAND_AUTHORING: dimensional consistency proof]",
            "S2": "[NEEDS_HAND_AUTHORING: well-posedness in declared regime]",
            "S3": "[NEEDS_HAND_AUTHORING: convergent solver class with rate]",
            "S4": "[NEEDS_HAND_AUTHORING: hardness-rule check on epsilon_fn]"
        },

        "ipfs_cid": None
    }
    return skeleton


def _build_l3_skeleton(l1: dict) -> dict:
    """Produce a valid L3 P-benchmark skeleton inheriting from L1."""
    aid = l1["artifact_id"]
    num = aid.split("-")[1]
    spec_range = l1.get("spec_range", {})
    center = spec_range.get("center_spec", {})

    skeleton = {
        "artifact_id": f"L3-{num}",
        "layer": "L3",
        "parent_l2": f"L2-{num}",
        "parent_l1": aid,
        "title": f"{l1.get('title', aid)} — P-benchmark Skeleton",
        "benchmark_type": "P_benchmark",
        "v2_v3_skeleton": True,
        "skeleton_note": "Auto-generated by scripts/generate_l2_l3_skeletons.py 2026-05-01. Per-Principle hand-authoring required to: (a) curate 20 dev instances + 10 holdout instances from a real dataset, (b) populate baselines with measured PSNR / accuracy / mIoU on the dev set, (c) write the M1-M6 anti-overfitting mechanism manifests, (d) compile S1-S4 gate evidence. See PWM_PART1_C1_STATUS.md for the per-Principle authoring queue.",

        "rho": 50,

        "dataset_registry": {
            "primary": "[NEEDS_HAND_AUTHORING: canonical dataset name + version]",
            "secondary": "[NEEDS_HAND_AUTHORING: alternative dataset, optional]",
            "construction_method": "[NEEDS_HAND_AUTHORING: crop / stitch / synthetic / clinical-cohort]",
            "num_dev_instances": 20,
            "holdout_instances": 10,
            "ground_truth_provenance": "[NEEDS_HAND_AUTHORING: how GT was established]"
        },

        "ibenchmarks": [
            {
                "tier": "T1_nominal",
                "rho": 1,
                "omega_tier": center.get("omega", {}),
                "dataset_description": "[NEEDS_HAND_AUTHORING: nominal-tier dataset description]",
                "epsilon": "[NEEDS_HAND_AUTHORING: nominal-tier threshold value]",
                "d_ibench": 0.15,
                "quality_thresholds": [
                    {"Q": 0.55, "tier": "Standard"},
                    {"Q": 0.75, "tier": "Strong"},
                    {"Q": 0.90, "tier": "Excellent"}
                ],
                "baselines": [
                    {"name": "[NEEDS_HAND_AUTHORING]", "metric": l1.get("error_metric", "PSNR_dB"), "score": None, "Q": None}
                ]
            }
        ],

        "scoring": {
            "primary_metric": l1.get("error_metric", "PSNR_dB"),
            "secondary_metric": l1.get("error_metric_secondary", "SSIM"),
            "scoring_formula": "[NEEDS_HAND_AUTHORING: how Q is computed from primary + secondary metrics]"
        },

        "anti_overfitting_mechanisms": {
            "M1_random_instantiation": "[NEEDS_HAND_AUTHORING: G(SHA256(h_sub)) generator spec]",
            "M2_convergence_check": "[NEEDS_HAND_AUTHORING: O(h^alpha) verification harness]",
            "M3_cross_instance_worst_case": "implements Track A stratified worst-case per pwm_overview1.md § 5",
            "M4_adversarial_instances": "implements community-submitted edge-case acceptance per pwm_overview1.md § 5",
            "M5_method_signature_diversity": "[NEEDS_HAND_AUTHORING: novelty multiplier for unseen primitive signatures]",
            "M6_s1_s4_gates": "[NEEDS_HAND_AUTHORING: per-instance S1-S4 gate harness]"
        },

        "hardness_rule_check": "[NEEDS_HAND_AUTHORING: proof that no expert baseline passes epsilon_fn everywhere in Omega]",

        "gate_class": l1.get("gate_class", "analytical"),
        "s1_s4_gates": ["PENDING", "PENDING", "PENDING", "PENDING"],
        "ipfs_cid": None,
        "ground_truth_cid": None
    }
    return skeleton


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--dry-run", action="store_true",
                    help="report what would be generated without writing")
    ap.add_argument("--force-overwrite", action="store_true",
                    help="overwrite existing L2/L3 skeleton files")
    args = ap.parse_args()

    repo = _repo_root()
    l1_files = _find_l1_files(repo)
    print(f"Found {len(l1_files)} L1 anchors in scope (L1-503..L1-531):")
    for p in l1_files:
        print(f"  {p.relative_to(repo)}")
    print()

    if args.dry_run:
        print("--dry-run: no files written")
        return 0

    written_l2 = 0
    written_l3 = 0
    skipped = 0
    for l1_path in l1_files:
        l1 = json.loads(l1_path.read_text())
        aid = l1["artifact_id"]
        num = aid.split("-")[1]
        # Use the same filename suffix convention as the L1 (e.g., "_qsm")
        stem = l1_path.stem  # e.g., "L1-503_qsm"
        suffix = stem[len("L1-503"):] if stem.startswith(f"L1-{num}") else ""

        l2_path = l1_path.parent / f"L2-{num}{suffix}.json"
        l3_path = l1_path.parent / f"L3-{num}{suffix}.json"

        if l2_path.exists() and not args.force_overwrite:
            skipped += 1
        else:
            l2_skel = _build_l2_skeleton(l1)
            l2_path.write_text(json.dumps(l2_skel, indent=2) + "\n")
            written_l2 += 1
            print(f"  L2 → {l2_path.relative_to(repo)}")

        if l3_path.exists() and not args.force_overwrite:
            skipped += 1
        else:
            l3_skel = _build_l3_skeleton(l1)
            l3_path.write_text(json.dumps(l3_skel, indent=2) + "\n")
            written_l3 += 1
            print(f"  L3 → {l3_path.relative_to(repo)}")

    print()
    print(f"L2 skeletons written: {written_l2}")
    print(f"L3 skeletons written: {written_l3}")
    print(f"Skipped (already existed; use --force-overwrite to replace): {skipped}")
    print()
    print("Each skeleton contains [NEEDS_HAND_AUTHORING: ...] placeholders.")
    print("Per-Principle filling is the next CPU agent or Bounty-#7 task.")
    print("Track progress in pwm-team/coordination/PWM_PART1_C1_STATUS.md.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
